config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'task_manager', :to => 'task_manager#index'

app/models/issue_log.rb
class IssueLog < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes

  belongs_to :issue

  safe_attributes 'issue_id',
    'project_id',
    'user_id',
    'date',
    'time'

  attr_accessible :issue_id, :project_id, :user_id, :date, :time

end

app/controllers/task_manager_controller.rb
class TaskManagerController < ApplicationController

  helper :sort
  include SortHelper

  before_filter :check_access

  def index
    sort_init 'issues.id', 'asc'
    sort_update %w(issues.id
      projects.name
      trackers.name
      issues.subject
      issues.estimated_hours
      issues.start_date
      users.firstname
      users.lastname
      members.hours_per_day)

@members = Member.all
@projects = Project.all.sort_by(&:name)
@users = User.all.sort_by(&:firstname)
@groups = Group.all.sort_by(&:lastname)
@project = Project.where(id: params[:project_id]).first if params[:project_id].present?
@unassigned_issues = @project.issues.open.where(assigned_to_id: nil) if params[:project_id].present?
@users = User.where(id: params[:user_id]) if params[:user_id].present?
@issues = Issue.open.where("project_id = ?", @project.id) if params[:project_id].present?

end

private
def check_access
  unless User.current.admin? || User.current.has_task_manager_access?
    redirect_to home_path
  end
end

end

app/helpers/task_manager_helper.rb
module TaskManagerHelper

  def find_member(user, project)
    Member.where("project_id = ? AND user_id = ?", project.id, user.id)
  end

  def find_issue_member(issue)
    Member.where("project_id = ? AND user_id = ?", issue.project.id, issue.assigned_to_id)
  end

  def find_issues(user, project)
    Issue.open.where("project_id = ? AND assigned_to_id = ?", project.id, user.id)
  end

  def find_time_entries(issue)
    TimeEntry.where("issue_id = ? and spent_on < ?", issue.id, Date.today)
  end

  # methods for users
  def members_hours_per_day(user, project)
    member = find_member(user, project).first
    member.hours_per_day if member && member.hours_per_day
  end

  def members_issue_count(user, project)
    find_issues(user, project).count
  end

  def members_estimated_time(user, project)
    estimated_time = 0
    find_issues(user, project).each do |i|
      estimated_time += i.estimated_hours if i.estimated_hours
    end
    return estimated_time if estimated_time > 0
  end

  # methods for tasks
  def issue_assigned_to_name(issue)
    issue.assigned_to ? issue.assigned_to.name : ' This task is not assigned.'
  end

  def assignees_hours_per_day(issue)
    member = find_issue_member(issue).first
    member.hours_per_day || 8.0
  end

  def issue_time_entries(issue)
    find_time_entries(issue).sum(:hours)
  end

  # others
  def has_unassigned_issues?(project)
    project.issues.map(&:assigned_to_id).include? nil
  end

  def has_overbooked_members?(project)
    overload = 0
    project.users.each do |u|
      overload += 1 if overload(u, project) == 'OVERBOOKED!'
    end
    return true if overload > 0
  end

  def has_underbooked_members?(project)
    underload = 0
    project.users.each do |u|
      underload += 1 if overload(u, project) == 'UNDERBOOKED!'
    end
    return true if underload > 0
  end

  # estimated due date
  def estimated_due_date(issue)

    return unless issue.estimated_hours && issue.start_date

    subtract_first_day_hours(issue)
    subtract_hours(issue)

    return @days.business_days.after(issue.start_date)

  end

  def first_day(issue)
    if issue.start_date && issue.start_time
      first_day_hours = 17 - (issue.start_time.hour + issue.start_time.min.to_f / 60)
    end
    return first_day_hours
  end

  def subtract_first_day_hours(issue)
    @estimated_time_left = issue.estimated_hours
    @member_hours = assignees_hours_per_day(issue)

    if issue.start_time && first_day(issue) < @member_hours
      @estimated_time_left -= @first_day_hours
    else
      @estimated_time_left -= @member_hours
    end

  end

  def subtract_hours(issue)
    @days = 0
    until @estimated_time_left < 0
      @estimated_time_left -= @member_hours
      @days += 1
    end
  end

  # time_left
  def time_left(issue)

    return 0 unless issue.estimated_hours && issue.start_date

    @time_left = issue.estimated_hours
    @memb_hours = assignees_hours_per_day(issue)
    @days_passed = (Date.today - issue.start_date).to_i - 1

    subtract_first_day_hours(issue) if issue.start_date < Date.today
    subtract_hours_left(issue) if @days_passed > 0

    return @time_left

  end

  def subtract_hours_left(issue)
    @time_left -= @memb_hours * @days_passed
  end

  def overload(user, project)
    issues = find_issues(user, project)
    member = find_member(user, project).first
    time = 0

    issues.each do |i|
      hours_per_day = assignees_hours_per_day(i)
      time_left(i) > hours_per_day ? time += hours_per_day : time += time_left(i)
    end

    return 'OVERBOOKED!' if time > @memb_hours
    return 'UNDERBOOKED!' if time < @memb_hours
    return 'OK'
  end

end

app/views/issues/_attributes.html.erb
<%= labelled_fields_for :issue, @issue do |f| %>

<div class="splitcontent">
<div class="splitcontentleft">
<% if @issue.safe_attribute?('status_id') && @allowed_statuses.present? %>
<p><%= f.select :status_id, (@allowed_statuses.collect {|p| [p.name, p.id]}), {:required => true},
                :onchange => "updateIssueFrom('#{escape_javascript update_issue_form_path(@project, @issue)}')" %></p>
<%= hidden_field_tag 'was_default_status', @issue.status_id, :id => nil if @issue.status == @issue.default_status %>
<% else %>
<p><label><%= l(:field_status) %></label> <%= @issue.status %></p>
<% end %>

<% if @issue.safe_attribute? 'priority_id' %>
<p><%= f.select :priority_id, (@priorities.collect {|p| [p.name, p.id]}), {:required => true}, :disabled => !@issue.leaf? %></p>
<% end %>

<% if @issue.safe_attribute? 'assigned_to_id' %>
<p><%= f.select :assigned_to_id, principals_options_for_select(@issue.assignable_users, @issue.assigned_to), :include_blank => true, :required => @issue.required_attribute?('assigned_to_id') %></p>
<% end %>

<% if @issue.safe_attribute?('category_id') && @issue.project.issue_categories.any? %>
<p><%= f.select :category_id, (@issue.project.issue_categories.collect {|c| [c.name, c.id]}), :include_blank => true, :required => @issue.required_attribute?('category_id') %>
<%= link_to(image_tag('add.png', :style => 'vertical-align: middle;'),
            new_project_issue_category_path(@issue.project),
            :remote => true,
            :method => 'get',
            :title => l(:label_issue_category_new),
            :tabindex => 200) if User.current.allowed_to?(:manage_categories, @issue.project) %></p>
<% end %>

<% if @issue.safe_attribute?('fixed_version_id') && @issue.assignable_versions.any? %>
<p><%= f.select :fixed_version_id, version_options_for_select(@issue.assignable_versions, @issue.fixed_version), :include_blank => true, :required => @issue.required_attribute?('fixed_version_id') %>
<%= link_to(image_tag('add.png', :style => 'vertical-align: middle;'),
            new_project_version_path(@issue.project),
            :remote => true,
            :method => 'get',
            :title => l(:label_version_new),
            :tabindex => 200) if User.current.allowed_to?(:manage_versions, @issue.project) %>
</p>
<% end %>
</div>

<div class="splitcontentright">
<% if @issue.safe_attribute? 'parent_issue_id' %>
<p id="parent_issue"><%= f.text_field :parent_issue_id, :size => 10, :required => @issue.required_attribute?('parent_issue_id') %></p>
<%= javascript_tag "observeAutocompleteField('issue_parent_issue_id', '#{escape_javascript auto_complete_issues_path(:project_id => @issue.project, :scope => Setting.cross_project_subtasks)}')" %>
<% end %>

<% if @issue.safe_attribute? 'start_date' %>
<p id="start_date_area">
  <%= f.text_field(:start_date, :size => 10, :disabled => !@issue.leaf?,
                   :required => @issue.required_attribute?('start_date')) %>
  <%= calendar_for('issue_start_date') if @issue.leaf? %>
</p>
<% end %>

<% if @issue.safe_attribute? 'start_time' %>
<p id="start_time_area">
  <%= f.text_field(:start_time, value: @issue.start_time.try(:strftime, "%I:%M %p"), :size => 10, :disabled => !@issue.leaf?,
                   :required => @issue.required_attribute?('start_time'), :class => "timepicker") %>
</p>

<% end %>

<% if @issue.safe_attribute? 'due_date' %>
<p id="due_date_area">
  <%= f.text_field(:due_date, :size => 10, :disabled => !@issue.leaf?,
                   :required => @issue.required_attribute?('due_date')) %>
  <%= calendar_for('issue_due_date') if @issue.leaf? %>
</p>
<% end %>

<% if @issue.safe_attribute? 'estimated_hours' %>
<p><%= f.text_field :estimated_hours, :size => 3, :disabled => !@issue.leaf?, :required => @issue.required_attribute?('estimated_hours') %> <%= l(:field_hours) %></p>
<% end %>

<% if @issue.safe_attribute?('done_ratio') && @issue.leaf? && Issue.use_field_for_done_ratio? %>
<p><%= f.select :done_ratio, ((0..10).to_a.collect {|r| ["#{r*10} %", r*10] }), :required => @issue.required_attribute?('done_ratio') %></p>
<% end %>
</div>
</div>

<% if @issue.safe_attribute? 'custom_field_values' %>
<%= render :partial => 'issues/form_custom_fields' %>
<% end %>

<% end %>

<% include_calendar_headers_tags %>


<script type='text/javascript'>

$(document).ready(function(){
    $('#issue_start_time.timepicker').timepicker({ timeFormat: 'HH:mm' });
});

</script>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'jquery.timepicker', :plugin => 'redmine_task_manager' %>
  <%= javascript_include_tag 'jquery.timepicker', :plugin => 'redmine_task_manager' %>
<% end %>

app/views/issues/_start_time.html.erb
<%= issue_fields_rows do |rows|

  unless @issue.disabled_core_fields.include?('start_time')
    rows.right l(:field_start_time), @issue.start_time.try(:strftime, "%I:%M %p"), :class => 'start-time'
  end

end %>

app/views/projects/settings/_members.html.erb
<% roles = Role.find_all_givable
   members = @project.member_principals.includes(:member_roles, :roles, :principal).to_a.sort %>

<p><%= link_to l(:label_member_new), new_project_membership_path(@project), :remote => true, :class => "icon icon-add" %></p>

<% if members.any? %>
<table class="list members">
  <thead>
    <tr>
      <th><%= l(:label_user) %> / <%= l(:label_group) %></th>
      <th><%= l(:label_role_plural) %></th>
      <th style="width:15%"></th>
      <%= call_hook(:view_projects_settings_members_table_header, :project => @project) %>
    </tr>
  </thead>
  <tbody>
  <% members.each do |member| %>
  <% next if member.new_record? %>
  <tr id="member-<%= member.id %>" class="<%= cycle 'odd', 'even' %> member">
  <td class="name <%= member.principal.class.name.downcase %>">
    <%= link_to_user member.principal %>
    (available <%= member.hours_per_day.to_f %> h/d)
  </td>

  <td class="roles">
    <span id="member-<%= member.id %>-roles"><%= member.roles.sort.collect(&:to_s).join(', ') %></span>
      <%= form_for(member,
                   {:as => :membership, :remote => true,
                    :url => membership_path(member),
                    :method => :put,
                    :html => { :id => "member-#{member.id}-roles-form", :class => 'hol' }}
             ) do |f| %>
        <p>
          <%= f.label l(:label_hours_per_day) %>
          <%= f.text_field :hours_per_day %>
          <hr/>
        </p>
        <p>
          <% roles.each do |role| %>
          <label>
            <%= check_box_tag('membership[role_ids][]',
                              role.id, member.roles.include?(role),
                              :id => nil,
                              :disabled => member.member_roles.detect {
                                 |mr| mr.role_id == role.id && !mr.inherited_from.nil?
                                 } ) %> <%= role %>
          </label><br />
          <% end %>
        </p>
        <%= hidden_field_tag 'membership[role_ids][]', '', :id => nil %>
        <p>
          <%= submit_tag l(:button_save), :class => "small" %>
          <%= link_to_function(l(:button_cancel),
                               "$('#member-#{member.id}-roles').show(); $('#member-#{member.id}-roles-form').hide(); return false;") %>
        </p>
      <% end %>
  </td>

  <td class="buttons">
      <%= link_to_function l(:button_edit),
                           "$('#member-#{member.id}-roles').hide(); $('#member-#{member.id}-roles-form').show(); return false;",
                           :class => 'icon icon-edit' %>
      <%= delete_link membership_path(member),
                      :remote => true,
                      :data => (!User.current.admin? && member.include?(User.current) ? {:confirm => l(:text_own_membership_delete_confirmation)} : {}) if member.deletable? %>
  </td>
  <%= call_hook(:view_projects_settings_members_table_row, { :project => @project, :member => member}) %>
  </tr>
<% end; reset_cycle %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/settings/_redmine_task_manager_settings.html.erb
<%= stylesheet_link_tag '/plugin_assets/redmine_task_manager/stylesheets/selectize.default.css' %>
<%= javascript_include_tag '/plugin_assets/redmine_task_manager/javascripts/selectize' %>
<p>
  <label><%= l('settings.allowed_groups_to_use_task_manager') %></label>
    <%= select_tag "settings[groups][]",
      options_from_collection_for_select(Group.all.sort, 'id', 'lastname', @settings['groups']
        ), :multiple => true, class: "selectize" %>

</p>
<p>
  <label><%= l('label_default_working_hours') %></label>
    <%= text_field_tag "start_at", value = 9 %> -
    <%= text_field_tag "finish_at", value = 17 %>

</p>
<style>
  div.box {
    overflow: initial;
  }
</style>
<script type="text/javascript">
  $(document).ready(function(){
    $('.selectize').selectize({
      plugins: ['remove_button']
    });
  });
</script>

app/views/task_manager/index.html.erb
<h2><%=l(:label_task_manager)%></h2>
&nbsp;
<%= form_tag(task_manager_path, :method => :get) do %>
<fieldset>
  <div class="splitcontentleft, col-sm-3">
    <label for='project_id'><%= l(:label_projects) %>:</label>
    <%= select_tag 'project_id', content_tag('option') + options_from_collection_for_select(@projects, :id, :name, params[:project_id].to_i),
    :onchange => "this.form.submit(); return false;", :class => "form-control" %>
  </div>
  <div class="splitcontentright">
    <div style="float: right" class="col-sm-6">
      <div class="splitcontentleft">
        <label for='group_id'><%= l(:label_groups) %>:</label>
        <%= select_tag 'group_id', content_tag('option') + options_from_collection_for_select(@groups, :id, :name, params[:group_id].to_i),
        :onchange => "this.form.submit(); return false;", :class => "form-control" %>
      </div>
      <div class="splitcontentright">
        <label for='user_id'><%= l(:label_users) %>:</label>
        <%= select_tag 'user_id', content_tag('option') + options_from_collection_for_select(@users, :id, :name, params[:user_id].to_i),
        :onchange => "this.form.submit(); return false;", :class => "form-control" %>
      </div>
    </div>
  </div>
</fieldset>
<% end %>
&nbsp;
<legend></legend>

<% if params[:user_id].present? || params[:project_id].present? || params[:group_id].present? %>
<div id="date" style="width: 38vh"></div>
&nbsp;
<% end %>

<% if @project %>
<div class="panel panel-default">
  <h3>&nbsp; Project: <%= @project.name %></h3>
  &nbsp;

  <% if has_underbooked_members?(@project) %>
  <div class="alert alert-warning">
    <strong><%= l(:label_underbooked_members) %></strong>
  </div>
  <% end %>

  <% if has_overbooked_members?(@project) %>
  <div class="alert alert-danger">
    <strong><%= l(:label_overbooked_members) %></strong>
  </div>
  <% end %>

  <% if has_unassigned_issues?(@project) %>
  <div class="alert alert-danger">
    <strong><%= l(:label_unassigned_tasks) %>:</strong>
    <br><br>
    <table id="tasks" class="table">
      <thead>
        <tr>
          <th><%= l(:field_id) %></th>
          <th><%= l(:field_tracker) %></th>
          <th><%= l(:field_subject) %></th>
          <th><%= l(:field_estimated_hours) %></th>
          <th><%= l(:field_start_date) %></th>
        </tr>
      </thead>
      <tbody>
        <% @unassigned_issues.each do |issue| %>
        <tr>
          <td><%= link_to issue.id, issue %></td>
          <td><%= issue.tracker %></td>
          <td><%= link_to issue.subject, issue %></td>
          <td><%= issue.estimated_hours %></td>
          <td><%= issue.start_date %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>
<% end %>

<% @users.each do |u| %>
<% if @project && @issues && !@issues.where(assigned_to_id: u.id).empty? %>
<div class="panel panel-default">
  <div class="splitcontentleft, col-sm-3">
    &nbsp;
    <h3><%= u.name %></h3>
  </div>
  <div class="splitcontentright, col-sm-9">
    &nbsp;
    <div class="panel panel-default">
      <table id="members" class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Project</th>
            <th>Project manager</th>
            <th>Hours per day</th>
            <th># of tasks</th>
            <th>Estimated time for tasks</th>
            <th>Workload</th>
          </tr>
        </thead>
        <tbody>
          <% u.projects.each do |p| %>
          <% if members_issue_count(u, p) > 0 %>
          <tr>
            <td><%= p.name %></td>
            <td>Menedżer</td>
            <td><%= members_hours_per_day(u, p) %></td>
            <td><%= members_issue_count(u, p) %></td>
            <td><%= members_estimated_time(u, p) %></td>
            <td><%= overload(u, p) %></td>
          </tr>
          <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <table id="tasks" class="table table-striped table-hover">
    <thead>
      <tr>
        <%= sort_header_tag('issues.id', :caption => l(:field_id)) %>
        <th>Project</th>
        <%= sort_header_tag('trackers.name', :caption => l(:field_tracker)) %>
        <%= sort_header_tag('issues.subject', :caption => l(:field_subject)) %>
        <%= sort_header_tag('issues.start_date', :caption => l(:field_start_date)) %>
        <th>Estimated due date</th>
        <%= sort_header_tag('issues.estimated_hours', :caption => l(:field_estimated_hours)) %>
        <th><%= l(:field_assignee_name) %></th>
        <th><%= l(:field_assignee_hours_per_day) %></th>
        <th>Logged time</th>
      </tr>
    </thead>
    <tbody>
      <% @issues.where(assigned_to_id: u.id).each do |issue| %>
      <tr>
        <td><%= link_to issue.id, issue %></td>
        <td><%= issue.project %></td>
        <td><%= issue.tracker %></td>
        <td><%= link_to issue.subject, issue %></td>
        <td><%= issue.start_date %></td>
        <td><%= estimated_due_date(issue) %></td>
        <td><%= issue.estimated_hours %></td>
        <td><%= issue_assigned_to_name(issue) %></td>
        <td><%= assignees_hours_per_day(issue) %></td>
        <td><%= issue_time_entries(issue) %></td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</fieldset>

<% end %>


<% content_for :header_tags do %>
<%= stylesheet_link_tag 'bootstrap', :plugin => 'redmine_task_manager' %>
<%= stylesheet_link_tag 'bootstrap-datetimepicker', :plugin => 'redmine_task_manager' %>
<%= javascript_include_tag 'jquery', :plugin => 'redmine_task_manager' %>
<%= javascript_include_tag 'moment', :plugin => 'redmine_task_manager' %>
<%= javascript_include_tag 'bootstrap', :plugin => 'redmine_task_manager' %>
<%= javascript_include_tag 'bootstrap-datetimepicker', :plugin => 'redmine_task_manager' %>
<%= javascript_include_tag 'bootstrap-datepaginator', :plugin => 'redmine_task_manager' %>
<%= javascript_include_tag 'task_manager', :plugin => 'redmine_task_manager' %>
<% end %>